-- ============================================
-- MIGRACIÓN: Tabla Maestro_Grupo
-- ============================================
-- Asignación maestro ↔ grupo. El director asigna grupos a profesores.
-- Ejecutar: psql -U postgres -d api_lector -f migrations/add_maestro_grupo_table.sql
-- ============================================

CREATE TABLE IF NOT EXISTS "Maestro_Grupo" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "maestro_id" bigint NOT NULL REFERENCES "Maestro"("id") ON DELETE CASCADE,
  "grupo_id" bigint NOT NULL REFERENCES "Grupo"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_MAESTRO_GRUPO_UNIQUE"
  ON "Maestro_Grupo" ("maestro_id", "grupo_id");
