-- ============================================
-- MIGRACIÓN: Tabla Grupo
-- ============================================
-- Grupos escolares por escuela (ej. 1A, 2B).
-- Solo el director puede crear y gestionar grupos de su escuela.
-- Ejecutar: psql -U postgres -d api_lector -f migrations/add_grupo_table.sql
-- ============================================

CREATE TABLE IF NOT EXISTS "Grupo" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "escuela_id" bigint NOT NULL REFERENCES "Escuela"("id"),
  "grado" bigint NOT NULL,
  "nombre" varchar(20) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_GRUPO_ESCUELA_GRADO_NOMBRE"
  ON "Grupo" ("escuela_id", "grado", "nombre");

CREATE INDEX IF NOT EXISTS "IDX_GRUPO_ESCUELA"
  ON "Grupo" ("escuela_id");
